### ISSUE TITLE
(make-uri) garbles byte strings

### ISSUE THREAD

**Issue by andrei-dubovik** [fukamachi/quri#30]
If I run the following,
```
(make-uri :defaults "http://smth.com/index.html"
          :query '(("id" . "%10")))
```
I get `http://smth.com/index.html?id=%2510`, as expected.

However, if I want want to make a query with a percent-encoded byte string, say
```
(let ((id (make-array 1 :element-type '(unsigned-byte 8))))
     (setf (elt id 0) 97)
     (make-uri :defaults "http://smth.com/index.html"
               :query `(("id" . ,id))))
```
I get `http://smth.com/index.html?id=%23%2897%29`, which is a percent encoding of the string "#(97)" instead of the expected `http://smth.com/index.html?id=a`.

**Comment by jathd** [comment]
The fix is pretty easy, but the question is whether this is intended or not. Right now, any value other than a string is first converted to a string via `write-to-string`, and then it's url-encoded. (BTW, this means that `make-uri` is affected by printer variables like `*print-base*`; is that a good idea?)

One solution would be to accept only strings and byte-vectors as values for a key, or maybe only a few extra types like integers and characters. Anything else is probably a bug anyway (who expects that putting, e.g., a structure class in there will result in anything sensible?). Users would just have to convert the value to a string themselves.

**Comment by Ambrevar** [comment]
I'm not the original author, only the current maintainer, so my guess is that @jathd is correct.
We have a  test suite to validate this, so I would accept a patch which:

- adds support for byte strings;
- errors out on anything else but strings and byte strings;
- is independent from `*print-base*`.

@jathd Would you like to send a patch?

**Comment by jathd** [comment]
@Ambrevar Sure, I'll send a pull request.

Should we also handle integers? (While making sure that `*print-base*` doesn't affect the result.) This is probably a common case, and not handling that case would invalidate one of the examples in the readme:
```
(make-uri :defaults "http://8arrow.org"
          :query '(("guest" . 1)))
```

**Comment by Ambrevar** [comment]
Yes, we must handle numbers indeed.

On second thought maybe handling any type could be the easiest
option.

There are many scalar types (non-struct, non-objects) in Common Lisp:
numbers (what about complex numbers?), strings, arrays, vectors, lists,
hash-tables, etc.  It's hard to foresee what the users would do with
them.

Then benefit of write-to-string is that the user can customize the
printer of an object so that `make-uri` can be called over it.

Thoughts?

**Comment by jathd** [comment]
Integers, why not, there's one "standard" way to print them (in base 10).

For anything more complex, I think it might be better to let the user convert it to a string by hand beforehand. Or maybe define a generic function `query-value-string` (or whatever) that we call on the value. The user can then define methods for their types.

**Comment by fukamachi** [comment]
I came to this problem late from a regression bug in other libraries due to `quri:url-encode-params` no longer accepting integers as arguments.
As an original author, I assumed only strings and numbers, not byte vectors, since URL-encode is not intended for binary.
I'd like to change it to make accept also numbers if there's no problems.

**Comment by Ambrevar** [comment]
Perfect, thanks!

I'll release a new version just now.
