### ISSUE TITLE
Comparison of uri-paths

### ISSUE THREAD

**Issue by aadcg** [fukamachi/quri#48]
I find the following misleading.

```
(quri:uri= (quri:uri "https://en.wikipedia.org/")
           (quri:uri "https://en.wikipedia.org"))
-> t
```

```
(quri:uri= (quri:uri "https://en.wikipedia.org/wiki/Potato/")
           (quri:uri "https://en.wikipedia.org/wiki/Potato"))
-> nil
```

Wouldn't you agree?

**Comment by Ambrevar** [comment]
Yup, but maybe it's what's required by the specs.

Does anyone know what the specs warrant here?

What do other languages do?

**Comment by Ambrevar** [comment]
In Go, https://en.wikipedia.org/ is different from https://en.wikipedia.org.

**Comment by jathd** [comment]
The spec ([RFC3986, 6.2.3 Scheme-Based Normalization](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.3)) gives an example of an `http` URI where they mention that the two URIs, with an without the "/", are equivalent:

> The syntax and semantics of URIs vary from scheme to scheme, as
   described by the defining specification for each scheme.
   Implementations may use scheme-specific rules, at further processing
   cost, to reduce the probability of false negatives.  For example,
   because the "http" scheme makes use of an authority component, has a
   default port of "80", and defines an empty path to be equivalent to
   "/", the following four URIs are equivalent:
>
>      http://example.com
>      http://example.com/
>      http://example.com:/
>      http://example.com:80/
>
>   In general, a URI that uses the generic syntax for authority with an
   empty path should be normalized to a path of "/".

Note the last sentence: "In general". 
I'm honestly not a fan of this kind of thing, except when the scheme is `http` (or `https`, that kind of thing). For unknown schemes, I think `foo://a` and `foo://a/` should *not* be treated as equivalent. Let the user of the API normalize it themselves if that's what they want.

**Comment by Ambrevar** [comment]
What about adding `uri-equal` which normalizes the empty path to "/", then have `uri=` not normalize anything?

**Comment by jathd** [comment]
> What about adding `uri-equal` which normalizes the empty path to "/", then have `uri=` not normalize anything?

Sounds good to me.

**Comment by Ambrevar** [comment]
Done in c38ffae5c9d5d010943c44ac2e79d6e4361b4751.
