### ISSUE TITLE
Coerce cl:pathname to string in URI's path

### ISSUE THREAD

**Issue by Ambrevar** [fukamachi/quri#78]
Quri allows `cl:pathname` in the URI path.  Is this really the desired behaviour?  @fukamachi ?

See this pitfall:

```lisp
(quri:uri= (quri:make-uri-file :path "foo") (quri:make-uri-file :path #p"foo"))
; => NIL
```

I believe this should be fixed.  What do you think @aartaka @aadcg ?

**Comment by aartaka** [comment]
I'd rather say: coerce all the paths to `cl:pathname` :P 

Rationale: 
- I'm guessing that pathnames are used to support arbitrary system-specific syntax for `file:` URLs (`foo\\bar\\baz` directories on Windows). 
- While it may be slightly weird for other types of URLs, it mostly works reliably enough.
- Pathnames are a portable way to represent arbitrarily branching filesystem-like hierarchies.
- URI paths are inspired and copy a lot of ideas from filesystems, thus pathnames are a good fit.
- CL has enough operations to deal with pathnames for `quri` API using pathnames to be a first-class citizen.
  - And even there wasn't enough operations, there are `uiop` and `nfiles` now.
- Using string paths and coercing paths to strings would make quite enough sense too.
- But using pathnames, although inconsistent, enables much more operations and has a matching semantics.

Given this, I'm more in favor of coercing all of the paths to pathnames. And, even if we coerce them to strings after all, let's have two path-fetching functions:
- One that always returns a string.
- And the one with pathname.

Adding to all the logic above, one can convert pathname to both string and another pathname, but it's not guaranteed that one can turn string into both string and pathname, because strings may lack information that pathnames often preserve.

**Comment by Ambrevar** [comment]
A big point against cl:pathnames, I believe, is that URI path are expected to be strings by everyone including the standard.  So not returning a string here is an obvious way to trip users (as we did...).



> * One that always returns a string.
> 
> * And the one with pathname.

Can you give an example?

**Comment by aadcg** [comment]
> A big point against cl:pathnames, I believe, is that URI path are expected to be strings by everyone including the standard.

This summarizes my view as well!

**Comment by aartaka** [comment]
Okay, we've re-discussed it yet again on the call, and I've checked some more things:
- Even on Windows, `file://` URLs are normalized to regular slash syntax.
- Windows drives are indeed represented as directories in `file://` URLs.
- Pathnames are serializable into strings and back in a reasonably portable way (UIOP).

Given these, strings are indeed a better, simpler, and more compliant representation. Let's coerce paths to strings.

**Comment by Ambrevar** [comment]
@aartaka Just found out that `quri` already has a dedicated `quri:uri-file-pathname`, so it's pretty clear that the original intent was to store strings, not `cl:pathname`s.

**Comment by aartaka** [comment]
All good then!
